name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build et Déploiement OVH
    runs-on: ubuntu-latest
    steps:
    - name: Récupération du code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Installation et Build
      run: |
        npm install --legacy-peer-deps
        npm run build

    - name: Synchronisation FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ./jeece_lp/
